project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Investments"
  author:
    - Ruochen Feng (rf2960)
    - Andrew Chen (yc4745)
  repo-url: https://github.com/rf2960/Investments.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


